### ISSUE TITLE
Game crashes when pressing keybind on 1.21.3

### ISSUE THREAD

**Issue by Ocraftj** [Saphjyr/ElytraChestplateSwapper#15]
I tried using this mod on 1.21.3 and my game immediately crashed. I'm assuming that when you updated it to this version you didn't change much of the code, but I'm pretty sure there were some technical changes in this version that could be the reason why it does this.

**Comment by coolsimulations** [comment]
Same problem here, seems the ElytraItem class has changed in 1.21.3

`java.lang.NoClassDefFoundError: net/minecraft/class_1770
	at knot//com.saphjyr.ElytraChestplateSwapper.InventoryUtils.isElytra(InventoryUtils.java:93)
	at knot//com.saphjyr.ElytraChestplateSwapper.InventoryUtils.swapChestplate(InventoryUtils.java:65)
	at knot//com.saphjyr.ElytraChestplateSwapper.SwapKeyBinding.onPressed(SwapKeyBinding.java:48)
	at knot//com.saphjyr.ElytraChestplateSwapper.SwapKeyBinding.method_23481(SwapKeyBinding.java:44)`

[crash-2024-11-26_13.58.19-client.txt](https://github.com/user-attachments/files/17912084/crash-2024-11-26_13.58.19-client.txt)

**Comment by werra11** [comment]
Same problem happens on 1.21.4

**Comment by mrM6TRIX6** [comment]
Same problem.

**Comment by Saphjyr** [comment]
1.21.2 is also affected
Fixed by #16 

Thank you @torobolin for the fix !
