### ISSUE TITLE
Crash on keybind being used in Creative search

### ISSUE THREAD

**Issue by JasonHorkles** [Saphjyr/ElytraChestplateSwapper#6]
I set my keybind to `e` and whenever I press `e` in the Creative search the game crashes - not sure how many other keybinds have this issue though
Edit: also happens on the default keybind

**Comment by JasonHorkles** [comment]
Here's the full error for more info
```
java.lang.NoSuchMethodError: 'int net.minecraft.class_481.method_2469()'
	at com.saphjyr.ElytraChestplateSwapper.SwapKeyBinding.onPressBypass(SwapKeyBinding.java:71)
	at com.saphjyr.ElytraChestplateSwapper.SwapKeyBinding.setPressedBypass(SwapKeyBinding.java:57)
	at net.minecraft.class_309.handler$zgc001$onKey(class_309.java:2074)
	at net.minecraft.class_309.method_1466(class_309.java)
	at net.minecraft.class_309.method_22678(class_309.java:455)
	at net.minecraft.class_1255.execute(class_1255.java:102)
	at net.minecraft.class_309.method_22676(class_309.java:455)
	at org.lwjgl.glfw.GLFWKeyCallbackI.callback(GLFWKeyCallbackI.java:44)
	at org.lwjgl.system.JNI.invokeV(Native Method)
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:190)
	at net.minecraft.class_1041.method_15998(class_1041.java:310)
	at net.minecraft.class_310.method_1523(class_310.java:1222)
	at net.minecraft.class_310.method_1514(class_310.java:781)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```
